### ISSUE TITLE
excample does not compile on 1.23.1

### ISSUE THREAD

**Issue by underwoodblog** [FluuxIO/mqtt#10]
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\client_manager.go:7:26: undefined: Client
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\client_manager.go:12:15: undefined: Client
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\client_manager.go:22:31: undefined: Client
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\client_manager.go:48:46: undefined: Message
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\receiver.go:14:24: undefined: Message
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\receiver.go:16:20: undefined: QOSResponse
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\receiver.go:25:58: undefined: Message
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\receiver.go:25:84: undefined: QOSResponse
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\receiver.go:32:53: undefined: QOSResponse
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\receiver.go:32:81: undefined: Message
..\pkg\mod\gosrc.io\mqtt@v0.0.0-20190226142036-a2ebb16fa266\receiver.go:32:81: too many errors
